### ISSUE TITLE
Big Refactor

### ISSUE THREAD

**Issue by mappum** [mappum/webcoin#13]
I'm moving a lot of the code in this repo into smaller modules, refactoring the APIs, and writing documentation. 

**TODO:**

- [ ] `peerhub`
  - [ ] Support multiple networks (so we can support Bitcoin, testnet, Litecoin, Zcash, etc.)
  - [ ] Support both WebRTC and Websocket transports
  - [ ] README
  - [ ] Tests
- [ ] `bitcoin-net`
  - [ ] Remove `bitcore-lib`/`bitcore-p2p` dependencies
  - [ ] Integrate with `bitcoin-protocol`
  - [ ] README
  - [ ] Tests
- [ ] `bitcoin-wallet`
  - [ ] Refactor for interfacing with other webcoin modules
  - [ ] README
  - [ ] Tests
- [ ] `webcoin`
  - [ ] Remove extracted code
  - [ ] Integrate with other webcoin modules
  - [ ] README
  - [ ] Tests

**Comment by cellvia** [comment]
had you considered a monorepo approach (a la Babel and others) ? I dont know enough about the codebase to recommend it, but curious if you had thought through it,

**Comment by keppel** [comment]
@cellvia looks like mappum answered this question in #19
